logging:
  level:
    sql: debug
    '[com.redmath.news]': debug
  pattern:
    level: "%5p ${HOSTNAME}"
#    console: 
  file:
    name: target/news.log
  

spring:
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  h2:
    console:
      enabled: true
  datasource:
    url: ${news.db.url}
    username: ${news.db.user}
    password: ${news.db.password}
#  security:
#    user:
#      name: test
#      password: test
#      roles: test

server:
  port: 9080

spring.profiles.include: dev

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always