spring:
  application:
    name: news
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  datasource:
    url: ${news.db.url}
    username: ${news.db.username}
    password: ${news.db.password}
  liquibase:
    contexts: ${news.liquibase.contexts:}
  h2:
    console:
      enabled: ${news.h2.console:false}

server:
  port: 9080
  servlet:
    context-path: /news

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: when-authorized
      
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}] ${HOSTNAME}"
  file:
    name: ${news.log.dir:target}/news.log
  level:
    sql: debug
    web: debug
    '[com.github.workshop]': debug

spring.profiles.include: local