name: maven verify

on:
  workflow_dispatch:
    inputs:
      branch:
        type: choice
        options: 
        - feature
        - develop
        - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout from feature branch
      uses: actions/checkout@v3
      with:
        ref: "${{ branch }}"

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B verify
